sudo: required

language: ruby

services: 
  - docker

env:
  global:
    - GOOGLE_SECRET=notarealsecret
    - GOOGLE_KEY=notarealkey

before_install:
 - docker-compose build
 - docker-compose up -d
 - bundle install 

script:
 - docker-compose exec web bundle exec rake db:test:prepare
 - docker-compose exec web bundle exec rspec

after_success:
  - docker-compose stop

after_failure:
  - docker-compose stop
  - docker-compose logs

# deploy:
#   provider: elasticbeanstalk
#   access_key_id: $ACCESSKEYID
#   secret_access_key:
#     secure: "$SECRETACCESSKEY"
#   region: "ca-central-1"  
#   app: "google-lti-connector"
#   env: "production"
#   bucket_name: "elasticbeanstalk-ca-central-1-882371129764"
#   on:
#     branch: master
  