sudo: required

language: ruby
services: 
  - docker

before_install:
  - sudo apt-get update
  - sudo apt-get install python3
  - docker-compose build
  - docker-compose up -d
  - bundle install 
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin

script:
 - docker-compose exec google-lti-web bundle exec rake db:test:prepare
 - docker-compose exec google-lti-web bundle exec rspec

after_success:
  - docker-compose stop

after_failure:
  - docker-compose stop
  - docker-compose logs
  
deploy:
  - on: 
    branch: master
      - docker --version  
      - pip install --user awscli
      - export PATH=$PATH:$HOME/.local/bin 
      - eval $(aws ecr get-login --region us-west-2) 
      - docker tag strongmind/google-lti-connector 448312246740.dkr.ecr.us-west-2.amazonaws.com/google-lti-connector:$TRAVIS_COMMIT
      - docker push 448312246740.dkr.ecr.us-west-2.amazonaws.com/google-lti-connector:$TRAVIS_COMMIT
