sudo: required

language: ruby

services: 
  - docker

env:
  global:
    - GOOGLE_SECRET=notarealsecret
    - GOOGLE_KEY=notarealkey

before_install:
 - docker-compose build
 - docker-compose up -d
 - bundle install 

script:
 - docker-compose exec web bundle exec rake db:test:prepare
 - docker-compose exec web bundle exec rspec

after_success:
  - docker-compose stop
  # - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  # - docker build -t strongmind/canvas-google-lti-connector .
  # - docker images
  # - docker tag strongmind/canvas-google-lti-connector:latest $DOCKER_USERNAME/strongmind/canvas-google-lti-connector:production
  # - docker push $DOCKER_USERNAME/strongmind/canvas-google-lti-connector:production

after_failure:
  - docker-compose stop
  - docker-compose logs

deploy:
  provider: elasticbeanstalk
  access_key_id: $AWSACCESSKEYID
  secret_access_key:
    secure: $AWSSECRETACCESSKEY
  region: us-west-2  
  app: "canvas-google-lti-connector"
  env: "CanvasGoogleLtiConnector-production"
  bucket_name: "elasticbeanstalk-us-west-2-448312246740"
  on:
    branch: master
  