sudo: required

language: ruby
services: 
  - docker

addons:
  apt:
    packages: 
      - build-essential
      - libpq-dev
      - libssl-dev
      - openssl
      - libffi-dev
      - zlib1g-dev
      - python3-pip
      - python3-dev

before_install:
  - COMMIT=${TRAVIS_COMMIT} docker-compose
  - docker-compose up -d
  - bundle install
  - pip3 install --user awscli
  - export PATH=$PATH:$HOME/.local/bin

script:
 - docker-compose exec google-lti-web bundle exec rake db:test:prepare
 - docker-compose exec google-lti-web bundle exec rspec

after_success:
  - docker-compose stop
  - docker --version  
  - export PATH=$PATH:$HOME/.local/bin 
  - eval $(aws ecr get-login --region us-west-2 --no-include-email)
  - docker ps
  # - docker tag strongmind/google-lti-connector:${TRAVIS_COMMIT} 448312246740.dkr.ecr.us-west-2.amazonaws.com/google-lti-connector:${TRAVIS_COMMIT}
  - docker push 448312246740.dkr.ecr.us-west-2.amazonaws.com/google-lti-connector:${TRAVIS_COMMIT} 

after_failure:
  - docker-compose stop
  - docker-compose logs
  