---
- hosts: 127.0.0.1
  connection: local
  vars_files:
     - 'vault.yml'
  tasks:
  - template:
      src: ./Dockerrun.aws.json.j2
      dest: ./Dockerrun.aws.json
    vars: 
      ECR_REPO: google-lti-connector

      