default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: <%= ENV['RDS_HOSTNAME'] %>
  database: <%= ENV['RDS_DB_NAME'] %>
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  port: <%= ENV.fetch('RDS_PORT', 5432) %>

production: &production
  <<: *default
  database: <%= ENV['RDS_DB_NAME'] %>_production

staging:
  <<: *production
  database: <%= ENV['RDS_DB_NAME'] %>_staging

development:
  <<: *default
  database: <%= ENV['RDS_DB_NAME'] %>_development

test:
  <<: *default
  database: <%= ENV['RDS_DB_NAME'] %>_test

qa:
  <<: *default
  database: <%= ENV['RDS_DB_NAME'] %>_qa
